### PR TITLE
Support Plone 5.2 and Python 3.7

### PR DESCRIPTION
**Pull request by ericof**
* Add Plone 5.2 testing
* Add compatibility method for FunctionalTestCase
* Update trove classifiers
* Update Changelog

### CODE REVIEW

**Comment by ericof** [comment]
@buchi ftw.slacker is a dependency of contentrules.slack and I will need a release with Plone 5.2 and Python 3 support, that is the reason for this PR :-)

**Comment by ericof** [comment]
@mbaechtold, @elioschmutz: Could you, please, take a look at this PR and prepare a release?

**Comment by mbaechtold** [comment]
I'll pass it on to the team.

**Review by jone — APPROVED** [review]
Thank you 🎉 
I will add the test setup for Python 3 (the current Plone 5.2 buildout still runs with 2.7) and then make a release.

**Comment by jone** [comment]
@ericof I have released `ftw.slacker = 1.1.0` with this change.

**Comment by ericof** [comment]
Thank you @jone!

**Pull request merged**
